# Generated by Django 3.2.13 on 2023-05-25 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.TextField(max_length=500)),
                ('tipo_accion', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
