# Generated by Django 3.2.13 on 2023-05-30 00:36

import apps.inventario.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='img_defecto.jpg', null=True, upload_to='marcas/', verbose_name='Image')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelo_created_by', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correlativo', models.CharField(max_length=8, unique=True)),
                ('nombre_item', models.CharField(max_length=50)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_garantia', models.DateField(blank=True, null=True)),
                ('caracteristica', models.TextField(default='', max_length=500)),
                ('comentarios', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('serial_number', models.CharField(max_length=60, unique=True)),
                ('ubicacion', models.TextField(default='', max_length=500)),
                ('imagen_item', models.ImageField(blank=True, default='img_defecto.jpg', null=True, upload_to=apps.inventario.models.get_item_image_folder, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ModeloItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_item_modelo', to='inventario.modeloitem')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_item_categoria', to='inventario.categoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_item_created_by', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_item_estado', to='inventario.estado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_item_proveedor', to='inventario.proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_item_actualizado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='historico_mantenimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cambio_partes', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('comentario', models.TextField(max_length=500)),
                ('imagen_mantenimiento', models.ImageField(default='img_defecto.jpg', upload_to=apps.inventario.models.get_item_image_folder_maintenance, verbose_name='Image_Maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimiento_creado_por', to=settings.AUTH_USER_MODEL)),
                ('inventario_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimiento_inventario', to='inventario.inventario_item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimiento_actualizado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
