# Generated by Django 3.2.13 on 2022-07-12 20:06

import apps.inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Asignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('unassigned_date', models.DateField(blank=True, null=True)),
                ('nota_asignacion', models.FileField(blank=True, null=True, upload_to=apps.inventario.models.get_user_notes_assigned_folder)),
                ('nota_descargo', models.FileField(blank=True, null=True, upload_to=apps.inventario.models.get_user_notes_unassinged_folder)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correlativo', models.CharField(max_length=8, unique=True)),
                ('nombre_item', models.CharField(max_length=50)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_garantia', models.DateField(blank=True, null=True)),
                ('caracteristica', models.TextField(default='', max_length=500)),
                ('comentarios', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('serial_number', models.CharField(max_length=60, unique=True)),
                ('ubicacion', models.TextField(default='', max_length=500)),
                ('imagen_item', models.ImageField(blank=True, default='img_defecto.jpg', null=True, upload_to=apps.inventario.models.get_item_image_folder, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='img_defecto.jpg', null=True, upload_to='marcas/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
