# Generated by Django 3.2.13 on 2022-08-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_item',
            name='estado',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('MANTENIMIENTO', 'Mantenimiento'), ('DESCARTADO', 'Descartado'), ('DISPONIBLE', 'Disponible'), ('GARANTIA', 'Garantia')], default='DISPONIBLE', max_length=25),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
