# Generated by Django 3.2.13 on 2023-03-08 22:35

import apps.inventario.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_inventario_item_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='historico_mantenimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cambio_partes', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('comentario', models.TextField(max_length=500)),
                ('imagen_mantenimiento', models.ImageField(upload_to=apps.inventario.models.get_item_image_folder_maintenance, verbose_name='Image_Maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimiento_creado_por', to=settings.AUTH_USER_MODEL)),
                ('inventario_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimiento_inventario', to='inventario.inventario_item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimiento_actualizado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
