# Generated by Django 3.2.13 on 2022-05-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Abierto', 'Open'), ('En progreso', 'In Progress'), ('En revisión', 'In Review'), ('Terminado', 'Done')], default='Abierto', max_length=25)),
                ('description', models.TextField(default='', max_length=500)),
                ('img_ticket', models.ImageField(default='img_defecto.jpg', upload_to='tickets/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
