# Generated by Django 3.2.13 on 2022-09-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20220905_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria_ticket',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
