# Generated by Django 3.2.13 on 2022-05-13 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20220512_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 55, 8, 965919, tzinfo=utc), verbose_name='creado en'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 55, 8, 965919, tzinfo=utc), verbose_name='actualizado en'),
        ),
    ]
