# Generated by Django 3.2.13 on 2022-06-02 04:13

import apps.tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_img_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='img_ticket',
            field=models.ImageField(default='img_defecto.jpg', upload_to=apps.tickets.models.get_user_image_folder, verbose_name='Image'),
        ),
    ]
