# Generated by Django 3.2.13 on 2022-05-13 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20220513_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 57, 55, 362758, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 57, 55, 362758, tzinfo=utc)),
        ),
    ]
