# Generated by Django 3.2.13 on 2022-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20220513_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='img_ticket',
            field=models.ImageField(default='img_defecto.jpg', upload_to='tickets/', verbose_name='Image'),
        ),
    ]
