# Generated by Django 3.2.13 on 2022-05-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20220513_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='username',
            new_name='user_id',
        ),
    ]
