# Generated by Django 3.2.13 on 2022-10-21 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_asignaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('DESCARGO', 'Descargo')], default='ASIGNADO', max_length=25)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asigna', to=settings.AUTH_USER_MODEL)),
                ('inventario_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario_item')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualiza', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignado_a', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
