# Generated by Django 3.2.13 on 2023-01-08 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial_asignaciones',
            name='usuario',
        ),
        migrations.AddField(
            model_name='historial_asignaciones',
            name='usuario',
            field=models.ManyToManyField(related_name='asignado_a', to=settings.AUTH_USER_MODEL),
        ),
    ]
