# Generated by Django 3.2.13 on 2022-09-07 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial_asignaciones',
            name='control_id',
        ),
        migrations.AddField(
            model_name='historial_asignaciones',
            name='status',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('DESCARGO', 'Descargo')], default='ASIGNADO', max_length=25),
        ),
        migrations.AddField(
            model_name='historial_asignaciones',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignado_a', to='usuarios.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='control_Asignaciones',
        ),
    ]
