# Generated by Django 3.2.13 on 2023-01-08 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asignaciones', '0002_auto_20230108_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial_asignaciones',
            name='usuario',
        ),
        migrations.AddField(
            model_name='historial_asignaciones',
            name='usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='asignado_a', to='auth.user'),
            preserve_default=False,
        ),
    ]
