# Generated by Django 3.2.13 on 2022-09-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_auto_20220907_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_asignaciones',
            old_name='assigned_at',
            new_name='assigned_date',
        ),
        migrations.RenameField(
            model_name='historial_asignaciones',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
