# Generated by Django 3.2.13 on 2022-10-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
