# Generated by Django 3.2.13 on 2022-10-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_departamentos_depto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(default='0601-1993-03787', max_length=15),
            preserve_default=False,
        ),
    ]
