# Generated by Django 3.2.13 on 2022-10-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_user_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='nombre_depto',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
